List products = [
  {
    "id" : 1,
    "img" : "vans-shoes_1.jpg",
    "name" : "Sneaker Unisex Vans Old Skool",
    "price" : "250.000",
    "mul_img" : [
      "vans-shoes_1.jpg",
      "vans-shoes_2.jpg",
      "vans-shoes_3.jpg",
      "vans-shoes_4.jpg",
    ], 
    "sizes" : [
      "40",
      "41",
      "42",
      "43",
      "44",
    ],
  },
  {
    "id" : 2,
    "img" : "nike-shoes_1.jpg",
    "name" : "Nike Air Force 1",
    "price" : "400.000",
    "mul_img" : [
      "nike-shoes_1.jpg",
      "nike-shoes_2.jpg",
      "nike-shoes_3.jpg",
      "nike-shoes_4.jpg",
    ], 
    "sizes" : [
      "40",
      "41",
      "42",
      "43",
      "44",
    ],
  },
  {
    "id" : 3,
    "img" : "adidas-shoes_1.jpg",
    "name" : "Adidas Breaknet White",
    "price" : "300.000",
    "mul_img" : [
      "adidas-shoes_1.jpg",
      "adidas-shoes_2.jpg",
      "adidas-shoes_3.jpg",
      "adidas-shoes_4.jpg",
    ], 
    "sizes" : [
      "40",
      "41",
      "42",
      "43",
      "44",
    ],
  },
  {
    "id" : 4,
    "img" : "puma-shoes_1.jpg",
    "name" : "Puma Caven White",
    "price" : "350.000",
    "mul_img" : [
      "puma-shoes_1.jpg",
      "puma-shoes_2.jpg",
      "puma-shoes_3.jpg",
      "puma-shoes_4.jpg",
    ], 
    "sizes" : [
      "40",
      "41",
      "42",
      "43",
      "44",
    ],
  },
  {
    "id" : 5,
    "img" : "asics-shoes_1.jpg",
    "name" : "Asics Dynablast Blue",
    "price" : "330.000",
    "mul_img" : [
      "asics-shoes_1.jpg",
      "asics-shoes_2.jpg",
      "asics-shoes_3.jpg",
      "asics-shoes_4.jpg",
    ], 
    "sizes" : [
      "40",
      "41",
      "42",
      "43",
      "44",
    ],
  },
];